version: 1
appRoot: frontend
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - echo "REACT_APP_API_ENDPOINT=$REACT_APP_API_ENDPOINT" > .env
        - cat .env
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
